INSERT INTO clientes
(CPF,NOME,ENDERECO,BAIRRO,CIDADE,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_DE_COMPRA,PRIMEIRA_COMPRA)
VALUES 
('1471156710','Érica Carvalho','R. Iriquitia','Jardins','São Paulo','80012212','19900901',27,'F',170000,24500,0),
('19290992743','Fernando Cavalcante','R. Dois de Fevereiro','Água Santa','Rio de Janeiro','22000000','20000212',18,'M',100000,20000,1),
('2600586709','César Teixeira','Rua Conde de Bonfim','Tijuca','Rio de Janeiro','22020001','20000312',18,'M',120000,22000,0);

SELECT * FROM sucos_vendas.tabela_de_produtos;

SELECT CODIGO_DO_PRODUTO AS CODIGO , NOME_DO_PRODUTO AS DESCRITOR,
EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM PRODUTOS);
				
INSERT INTO produtos
SELECT CODIGO_DO_PRODUTO AS CODIGO , NOME_DO_PRODUTO AS DESCRITOR,
SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM PRODUTOS);


SELECT * FROM sucos_vendas.tabela_de_clientes;

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO,
LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA
FROM sucos_vendas.tabela_de_clientes
WHERE CPF NOT IN (SELECT CPF FROM CLIENTES);

INSERT INTO clientes
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO,
LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA
FROM sucos_vendas.tabela_de_clientes
WHERE CPF NOT IN (SELECT CPF FROM CLIENTES);

SELECT * FROM vendedores;